/**
 * One-shot maintainer: rebuild Sales Invoices.final-schema.json fields[] per canonical layout.
 * Run: npx tsx scripts/rewrite-sales-invoice-final-schema.ts
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outPath = path.join(root, "output", "schema-discovery", "Sales Invoices.final-schema.json");

type F = {
  section: string;
  fieldName: string;
  fieldType: string;
  description: string;
  required: boolean;
  provenance?: string;
  exampleValue?: string;
  alternateLabels?: string[];
};

const fields: F[] = [
  // --- Compliance (canonical for AD, CIN, GSTIN, PAN, IRN, rotation, signature) ---
  {
    section: "Compliance",
    fieldName: "AD Code",
    fieldType: "string",
    description: "Authorized Dealer Code for export remittance",
    required: false,
    provenance: "merged",
    alternateLabels: ["AD No"],
  },
  {
    section: "Compliance",
    fieldName: "CIN No",
    fieldType: "string",
    description: "Corporate Identity Number",
    required: true,
    exampleValue: "U74999KA2017PTC128777",
    provenance: "merged",
    alternateLabels: ["CIN No", "CIN No U74999KA2017PTC128777"],
  },
  {
    section: "Compliance",
    fieldName: "GSTIN",
    fieldType: "string",
    description: "Goods and Services Tax Identification Number (canonical; not duplicated in header/entities/footer)",
    required: true,
    exampleValue: "29AABCZ1506C1ZN",
    provenance: "merged",
    alternateLabels: ["GST No", "GST No 29AABCZ1506C1ZN", "GST No."],
  },
  {
    section: "Compliance",
    fieldName: "IRN Number",
    fieldType: "string",
    description:
      "Invoice Reference Number (e-invoice). **Always extract when present** — check the **IRN Number** label, e-invoice metadata block, and **QR code** area / embedded IRN string on the PDF.",
    required: false,
    provenance: "merged",
    alternateLabels: ["IRN Number", "IRN", "Irn"],
  },
  {
    section: "Compliance",
    fieldName: "PAN No",
    fieldType: "string",
    description: "Permanent Account Number (canonical)",
    required: true,
    exampleValue: "AABCZ1506C",
    provenance: "merged",
    alternateLabels: ["PAN No", "PAN / PAN No", "PAN No AABCZ1506C"],
  },
  {
    section: "Compliance",
    fieldName: "Rotation No",
    fieldType: "string",
    description: "Customs rotation number",
    required: false,
    provenance: "original",
  },
  {
    section: "Compliance",
    fieldName: "Signature",
    fieldType: "boolean",
    description:
      "Whether an authorized signatory stamp/signature is visibly present on the PDF (true/false string ok)",
    required: true,
    provenance: "original",
  },

  // --- Entities (no duplicate GSTIN/PAN/IEC here; no concatenated exporter; no duplicate consignee blocks) ---
  {
    section: "Entities",
    fieldName: "Buyer Name",
    fieldType: "string",
    description: "Name of the buyer",
    required: true,
    provenance: "merged",
    alternateLabels: ["Buyer"],
  },
  {
    section: "Entities",
    fieldName: "Buyer Address",
    fieldType: "address",
    description: "Buyer address when distinct from consignee (else may match consignee block)",
    required: false,
    provenance: "merged",
    alternateLabels: ["Buyer", "Bill To", "Sold To"],
  },
  {
    section: "Entities",
    fieldName: "Consignee Name",
    fieldType: "string",
    description: "Name of the consignee",
    required: true,
    exampleValue: "Unimacts Manufacturing Mx.,LLC",
    provenance: "merged",
    alternateLabels: ["Consignee", "Unimacts Manufacturing Mx.,LLC"],
  },
  {
    section: "Entities",
    fieldName: "Consignee Address",
    fieldType: "address",
    description: "Full address of the consignee",
    required: true,
    provenance: "original",
  },
  {
    section: "Entities",
    fieldName: "Exporter Name",
    fieldType: "string",
    description: "Legal name of the exporting entity",
    required: true,
    exampleValue: "ZETWERK MANUFACTURING BUSINESSES PRIVATE LIMITED",
    provenance: "merged",
    alternateLabels: ["Exporter", "ZETWERK MANUFACTURING BUSINESSES PRIVATE LIMITED"],
  },
  {
    section: "Entities",
    fieldName: "Exporter Address",
    fieldType: "address",
    description: "Full registered address of the exporter",
    required: true,
    provenance: "merged",
    alternateLabels: [
      "D. No: 1-6-2, Main Road, S-Heights - 3rd Floor, Chowdarypet Area,Near Maruthi Nagar Arch, Guntur, Guntur District - 522006, Andhra Pradesh. India",
    ],
  },
  {
    section: "Entities",
    fieldName: "IEC",
    fieldType: "string",
    description: "Import Export Code of the exporter (canonical)",
    required: true,
    provenance: "merged",
    alternateLabels: ["IEC#", "IEC#: AABCZ1506C"],
  },
  {
    section: "Entities",
    fieldName: "Notify Party",
    fieldType: "string",
    description: "Notify party details",
    required: false,
    provenance: "original",
  },
  {
    section: "Entities",
    fieldName: "Ship To",
    fieldType: "address",
    description: "Delivery address (may differ from consignee)",
    required: true,
    provenance: "merged",
    alternateLabels: ["Ship To"],
  },

  // --- Financial (canonical bank + tax + incoterm code + payment terms) ---
  {
    section: "Financial",
    fieldName: "Bank Name",
    fieldType: "string",
    description: "Beneficiary bank name for remittance",
    required: false,
    provenance: "merged",
    alternateLabels: ["Account bank", "Bank Name", "Bank Name ICICI Bank"],
  },
  {
    section: "Financial",
    fieldName: "Bank account no",
    fieldType: "string",
    description: "Exporter bank account number",
    required: true,
    exampleValue: "000251000256",
    provenance: "merged",
    alternateLabels: ["Account number", "Bank A/c No", "Bank A/c No 000251000256"],
  },
  {
    section: "Financial",
    fieldName: "Bank branch",
    fieldType: "string",
    description: "Bank branch for remittance",
    required: true,
    provenance: "merged",
    alternateLabels: ["Branch name", "Branch Name"],
  },
  {
    section: "Financial",
    fieldName: "Currency",
    fieldType: "string",
    description: "ISO 4217 currency code (e.g. USD) after normalization",
    required: true,
    provenance: "original",
  },
  {
    section: "Financial",
    fieldName: "IFSC Code",
    fieldType: "string",
    description: "Indian Financial System Code",
    required: true,
    exampleValue: "ICIC0000002",
    provenance: "merged",
    alternateLabels: ["IFSC Code", "IFSC Code ICIC0000002"],
  },
  {
    section: "Financial",
    fieldName: "SWIFT Code",
    fieldType: "string",
    description: "SWIFT/BIC for international transfers (canonical; no duplicate Bank SWIFT)",
    required: true,
    exampleValue: "ICICINBBCTS",
    provenance: "merged",
    alternateLabels: ["SWIFT", "Swift Code", "Swift Code ICICINBBCTS"],
  },
  {
    section: "Financial",
    fieldName: "Incoterms",
    fieldType: "string",
    description: "Incoterm code only (e.g. FOB, EXW) — not full sentence blocks",
    required: true,
    provenance: "merged",
    alternateLabels: ["FOB BY SEA", "Terms of Delivery", "Transportation Term - FOB"],
  },
  {
    section: "Financial",
    fieldName: "Payment terms",
    fieldType: "string",
    description: "Agreed payment schedule / terms",
    required: true,
    provenance: "merged",
    alternateLabels: [
      "PAYMENT TERM",
      "Payment Term - 90 Days LC",
      "Payment Term - 90 days On SHIPMENT DATE",
      "Terms of Delivery and Payment",
    ],
  },
  {
    section: "Financial",
    fieldName: "Tax Amount",
    fieldType: "currency",
    description: "Total integrated tax amount for the invoice (canonical total tax)",
    required: true,
    provenance: "merged",
    alternateLabels: ["Tax", "Total Tax"],
  },
  {
    section: "Financial",
    fieldName: "Cess",
    fieldType: "currency",
    description: "Cess tax amount",
    required: false,
    provenance: "merged",
    alternateLabels: ["Cess"],
  },
  {
    section: "Financial",
    fieldName: "Taxable Value",
    fieldType: "currency",
    description: "Total taxable value before tax (canonical)",
    required: true,
    provenance: "merged",
    alternateLabels: ["Taxable Value"],
  },
  {
    section: "Financial",
    fieldName: "Total Amount",
    fieldType: "currency",
    description: "Grand total invoice amount",
    required: true,
    provenance: "merged",
    alternateLabels: ["Total", "Total Value", "Total Invoice Value", "Grand Total"],
  },

  // --- Footer (no bank/tax IDs; declaration not duplicated) ---
  {
    section: "Footer",
    fieldName: "Signatory Designation",
    fieldType: "string",
    description: "Job title of the authorized signatory",
    required: false,
    provenance: "merged",
    alternateLabels: ["Managing Director"],
  },
  {
    section: "Footer",
    fieldName: "Signatory Name",
    fieldType: "string",
    description: "Name of the authorized signatory",
    required: false,
    provenance: "merged",
    alternateLabels: ["Rama Krishna Immadi"],
  },
  {
    section: "Footer",
    fieldName: "Digital Signature Date",
    fieldType: "date",
    description: "Signature date (use for wet or digital signature)",
    required: false,
    provenance: "original",
    alternateLabels: ["Date"],
  },
  {
    section: "Footer",
    fieldName: "Digital Signature Location",
    fieldType: "string",
    description: "Signature location",
    required: false,
    provenance: "merged",
    alternateLabels: ["Location", "Location: Bengaluru"],
  },
  {
    section: "Footer",
    fieldName: "Digital Signature Timestamp",
    fieldType: "string",
    description:
      "**Time only** (e.g. 11:58:14 or 20:48:50). Do not repeat the date — use `digitalSignatureDate` for the date portion.",
    required: false,
    provenance: "merged",
    alternateLabels: ["Date: 2025.08.14 20:48:50", "Date: 2025.09.30 11:58:14"],
  },
  {
    section: "Footer",
    fieldName: "Receivables assignment notice",
    fieldType: "string",
    description: "Receivables assignment notice text",
    required: false,
    provenance: "merged",
    alternateLabels: [
      "These receivables have been assigned to Linklogis International Company Limited",
    ],
  },
  {
    section: "Footer",
    fieldName: "DIN Number",
    fieldType: "string",
    description: "Director Identification Number",
    required: false,
    provenance: "merged",
    alternateLabels: ["DIN"],
  },
  {
    section: "Footer",
    fieldName: "Digital Signature Status",
    fieldType: "string",
    description: "Validation status of the digital signature",
    required: false,
    provenance: "novel_remap",
  },
  {
    section: "Footer",
    fieldName: "Receivables Assignment Beneficiary",
    fieldType: "string",
    description:
      "Legal name of the assignee (e.g. Linklogis International Company Limited). **Required whenever** `receivablesAssignmentNotice` / assignment clause text is present on the PDF — extract the named entity from that same clause.",
    required: false,
    provenance: "novel_remap",
  },
  // --- Header (invoice id, shipping bill, PO, Zetwerk ref — no duplicate GSTIN/IEC/buyer ref/exporter ref/branch) ---
  {
    section: "Header",
    fieldName: "Invoice No",
    fieldType: "string",
    description: "Unique invoice identifier (canonical)",
    required: true,
    exampleValue: "KA/UM/2526/00842",
    provenance: "merged",
    alternateLabels: ["Invoice No.", "Invoice No. & Date", "Invoice No. KA/UM/2526/00842"],
  },
  {
    section: "Header",
    fieldName: "Invoice Date",
    fieldType: "date",
    description: "Invoice date (canonical)",
    required: true,
    exampleValue: "30-Sep-2025",
    provenance: "merged",
    alternateLabels: ["Invoice Date", "Invoice Date 30-Sep-2025"],
  },
  {
    section: "Header",
    fieldName: "Buyer PO No",
    fieldType: "string",
    description: "Buyer purchase order number (canonical)",
    required: true,
    exampleValue: "UNMF-PO-000001808",
    provenance: "merged",
    alternateLabels: [
      "Buyer's PO No.",
      "Buyer's PO No. UNMF-PO-000001808",
      "Buyer Order No.",
      "Buyers Order No.",
    ],
  },
  {
    section: "Header",
    fieldName: "Buyer PO Date",
    fieldType: "date",
    description: "Buyer PO date (canonical)",
    required: true,
    provenance: "merged",
    alternateLabels: ["Buyer's PO Date", "Buyer’s PO Date", "Buyers Order Date"],
  },
  {
    section: "Header",
    fieldName: "Zetwerk Ref",
    fieldType: "string",
    description: "Internal Zetwerk reference (merged from former Tax Invoice block)",
    required: true,
    exampleValue: "CN-KA36744",
    provenance: "merged",
    alternateLabels: ["Zetwerk Ref#", "Zetwerk Ref# CN-KA36744"],
  },
  {
    section: "Header",
    fieldName: "Shipping Bill No",
    fieldType: "string",
    description: "ICEGATE Shipping Bill number (canonical)",
    required: true,
    provenance: "merged",
    alternateLabels: ["Shipping Bill No."],
  },
  {
    section: "Header",
    fieldName: "Shipping Bill Date",
    fieldType: "date",
    description: "Shipping Bill date",
    required: false,
    provenance: "merged",
    alternateLabels: ["Shipping Bill Date"],
  },
  {
    section: "Header",
    fieldName: "Exporter Name",
    fieldType: "string",
    description: "Exporter name as printed in header block",
    required: true,
    exampleValue: "ZETWERK MANUFACTURING BUSINESSES PRIVATE LIMITED",
    provenance: "merged",
    alternateLabels: ["ZETWERK MANUFACTURING BUSINESSES PRIVATE LIMITED"],
  },
  {
    section: "Header",
    fieldName: "Exporter Email",
    fieldType: "string",
    description: "Exporter contact email",
    required: false,
    provenance: "merged",
  },
  {
    section: "Header",
    fieldName: "Invoice type",
    fieldType: "string",
    description:
      "Zetwerk / e-invoice: the full **banner or declaration headline** (e.g. \"SUPPLY MEANT FOR EXPORT ON PAYMENT OF INTEGRATED TAX\"). Do NOT use the small section title \"Tax Invoice\" alone — that is only a layout label.",
    required: false,
    provenance: "merged",
  },
  {
    section: "Header",
    fieldName: "LUT/ARN No",
    fieldType: "string",
    description: "LUT / ARN for GST",
    required: true,
    exampleValue: "AD290324064993N",
    provenance: "merged",
    alternateLabels: ["LUT/ARN No.", "LUT/ARN No. AD290324064993N"],
  },
  {
    section: "Header",
    fieldName: "Issue Date",
    fieldType: "date",
    description: "Issue date for export reference",
    required: false,
    exampleValue: "30-Mar-2024",
    provenance: "merged",
    alternateLabels: ["Issue Date", "Issue Date 30-Mar-2024"],
  },
  {
    section: "Header",
    fieldName: "Other references",
    fieldType: "string",
    description: "Additional references (not PO; not Zetwerk ref)",
    required: false,
    exampleValue: "CN-KA36975",
    provenance: "merged",
    alternateLabels: ["Other Reference(s)", "Zetwerk Ref#", "Zetwerk Ref# CN-KA36975"],
  },
  {
    section: "Header",
    fieldName: "Dispatched Through",
    fieldType: "string",
    description: "Dispatch mode or carrier",
    required: false,
    provenance: "original",
  },

  // --- Line Items ---
  {
    section: "Line Items",
    fieldName: "HSN Code",
    fieldType: "string",
    description: "HSN without dots (normalized)",
    required: true,
    exampleValue: "73089010",
    provenance: "merged",
    alternateLabels: ["HSNC - 73089010"],
  },
  {
    section: "Line Items",
    fieldName: "HSN Code (Destination)",
    fieldType: "string",
    description: "Destination HSN if distinct",
    required: false,
    provenance: "novel_remap",
  },
  {
    section: "Line Items",
    fieldName: "Product code",
    fieldType: "string",
    description:
      "SKU / internal part code only (e.g. WB.G.FG.CB141.6085.1300.A.IN). Do not put the short product title here — use `productDescription`.",
    required: false,
    provenance: "original",
  },
  {
    section: "Line Items",
    fieldName: "Product Description",
    fieldType: "string",
    description:
      "Short product **name** only (e.g. INTERIOR PILE). No HSN, no full SKU/part code, no long spec — use `productCode` / `hsnCode` / `productSpecification`.",
    required: true,
    provenance: "merged",
    alternateLabels: ["Description", "Description of Goods", "Sl. Description"],
  },
  {
    section: "Line Items",
    fieldName: "Product Specification",
    fieldType: "string",
    description:
      "Technical spec **only**: dimensions, grade, material, finish, length, etc. (e.g. W6 X 8.5 - 13ft. Long, HDG, KITT SOLAR NO COLOR). **No** origin/certs (e.g. not “100% Indian steel, smelted in India”) — those are not product specs.",
    required: false,
    provenance: "merged",
  },
  {
    section: "Line Items",
    fieldName: "Product Part Number",
    fieldType: "string",
    description: "Manufacturer part number",
    required: false,
    provenance: "merged",
  },
  {
    section: "Line Items",
    fieldName: "Product SKU",
    fieldType: "string",
    description: "SKU",
    required: false,
    provenance: "original",
  },
  {
    section: "Line Items",
    fieldName: "Product Marks",
    fieldType: "string",
    description:
      "Marks **for this line** from the item table. For **single-line** invoices, all marks go here; leave `shipment.marksAndNumbers` null.",
    required: false,
    provenance: "merged",
    alternateLabels: ["Mark No."],
  },
  {
    section: "Line Items",
    fieldName: "No of Packages",
    fieldType: "number",
    description: "Package count **for this line** (e.g. 18, 4, 1) — not the shipment total only",
    required: false,
    provenance: "merged",
    alternateLabels: ["No. of Pkg", "Pkgs", "PKG"],
  },
  {
    section: "Line Items",
    fieldName: "Quantity",
    fieldType: "number",
    description: "Quantity",
    required: true,
    provenance: "merged",
    alternateLabels: ["Qty", "Quantity"],
  },
  {
    section: "Line Items",
    fieldName: "Unit",
    fieldType: "string",
    description: "Unit of measure (normalized uppercase e.g. NOS)",
    required: true,
    provenance: "merged",
    alternateLabels: ["NOS"],
  },
  {
    section: "Line Items",
    fieldName: "Rate",
    fieldType: "currency",
    description: "Unit rate / unit price (single field; do not duplicate as unitPrice)",
    required: true,
    provenance: "merged",
    alternateLabels: ["Rate", "Unit Rate", "Unit Price"],
  },
  {
    section: "Line Items",
    fieldName: "Line total",
    fieldType: "currency",
    description: "Line amount (normalized)",
    required: true,
    provenance: "merged",
    alternateLabels: ["Amount", "Total Price"],
  },
  {
    section: "Line Items",
    fieldName: "Tax rate",
    fieldType: "percentage",
    description: "Tax percentage for the line",
    required: false,
    provenance: "merged",
    alternateLabels: ["+ Tax 18%", "Tax Percentage / Tax Rate"],
  },
  {
    section: "Line Items",
    fieldName: "Tax amount per line",
    fieldType: "currency",
    description: "Tax amount for this line (normalized)",
    required: false,
    provenance: "original",
    alternateLabels: ["Tax Amount per Line"],
  },
  {
    section: "Line Items",
    fieldName: "Kind of Pkg",
    fieldType: "string",
    description:
      "Line packaging type as printed (e.g. PKGS, NOS, BDL). Extract from the line row or qty/pkg column — never leave null when the PDF shows PKGS/NOS/etc.",
    required: false,
    provenance: "novel_remap",
    alternateLabels: ["Kind of Pkg", "PKGS", "Pkg"],
  },

  // --- Shipment (merged logistics; no duplicate incoterms here) ---
  {
    section: "Shipment",
    fieldName: "Country of Final Destination",
    fieldType: "string",
    description: "Final destination country (normalized title case / ISO name)",
    required: true,
    provenance: "merged",
    alternateLabels: ["Country of Final Destination", "Country of Final Destination United States of America"],
  },
  {
    section: "Shipment",
    fieldName: "Country of Origin",
    fieldType: "string",
    description: "Country of origin of goods (canonical; not in compliance)",
    required: true,
    provenance: "merged",
    alternateLabels: ["Country of Origin of Goods", "Country of Origin of Goods India"],
  },
  {
    section: "Shipment",
    fieldName: "Final Destination",
    fieldType: "string",
    description: "Final destination place",
    required: true,
    provenance: "merged",
    alternateLabels: ["Final Destination", "Final Destination Chicago,USA"],
  },
  {
    section: "Shipment",
    fieldName: "Place of Receipt",
    fieldType: "string",
    description: "Place of receipt by pre-carrier",
    required: true,
    provenance: "merged",
    alternateLabels: [
      "Place of Receipt by Pre-Carrier",
      "Place of Receipt by Pre-Carrier Gummidipoondi, Tamil Nadu",
    ],
  },
  {
    section: "Shipment",
    fieldName: "Port of Discharge",
    fieldType: "string",
    description: "Port of discharge",
    required: true,
    provenance: "merged",
    alternateLabels: ["Port of Discharge", "Port of Discharge Chicago,USA"],
  },
  {
    section: "Shipment",
    fieldName: "Port of Loading",
    fieldType: "string",
    description: "Port of loading",
    required: true,
    provenance: "merged",
    alternateLabels: ["Port of Loading", "Port of Loading Chennai", "Port of Loading Mundra Port"],
  },
  {
    section: "Shipment",
    fieldName: "Vessel/Flight No",
    fieldType: "string",
    description: "Vessel or flight",
    required: true,
    provenance: "merged",
    alternateLabels: ["Vessel/Flight No."],
  },
  {
    section: "Shipment",
    fieldName: "Gross Weight",
    fieldType: "weight",
    description: "Gross weight (merged from logistics)",
    required: false,
    provenance: "original",
  },
  {
    section: "Shipment",
    fieldName: "No of Packages",
    fieldType: "number",
    description: "Package count — numeric only after normalization",
    required: true,
    provenance: "merged",
    alternateLabels: ["No. of Pkg"],
  },
  {
    section: "Shipment",
    fieldName: "Marks and numbers",
    fieldType: "string",
    description:
      "Invoice-level marks summary when **multiple line items** share a combined marks block. For **single-line** invoices use **null** here — marks belong in `lineItems[].productMarks` only.",
    required: false,
    provenance: "merged",
    alternateLabels: ["Mark No."],
  },
  {
    section: "Shipment",
    fieldName: "Package description",
    fieldType: "string",
    description: "Kind/count of packages text",
    required: true,
    provenance: "merged",
    alternateLabels: ["Kind of Pkg", "No. & Kind of Pkgs Bundles"],
  },
  {
    section: "Shipment",
    fieldName: "Pre-Carriage by",
    fieldType: "string",
    description: "Pre-carriage mode",
    required: false,
    provenance: "original",
  },
];

const existing = JSON.parse(fs.readFileSync(outPath, "utf8")) as Record<string, unknown>;
existing.fields = fields;
existing.statistics = {
  ...(existing.statistics as object),
  outputFieldCount: fields.length,
};
existing.summary =
  "Canonical Sales Invoices schema: deduplicated GSTIN/PAN/IEC/bank/SWIFT/shipping-bill/invoice IDs; merged Tax Invoice into Header; merged Logistics into Shipment; single financial tax/total fields; normalized keys for extraction.";

fs.writeFileSync(outPath, JSON.stringify(existing, null, 2) + "\n", "utf8");
console.log("Wrote", outPath, "fields:", fields.length);
