CREATE SCHEMA IF NOT EXISTS "aiextraction";

CREATE TABLE IF NOT EXISTS "aiextraction"."isf_extractions" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "document_id" TEXT NOT NULL,
  "source" TEXT,
  "document_type" TEXT,
  "importer_name" TEXT,
  "form_submitted_by_name" TEXT,
  "form_submitted_by_company" TEXT,
  "telephone" TEXT,
  "fax" TEXT,
  "email" TEXT,
  "transaction_id" TEXT,
  "bl_type" TEXT,
  "master_bl_number" TEXT,
  "bond_type" TEXT,
  "bond_term" TEXT,
  "have_a_bond_with_cbp" TEXT,
  "filer_document_number" TEXT,
  "filer_document_type" TEXT,
  "agent_filer_code" TEXT,
  "scac_code" TEXT,
  "house_bl_number" TEXT,
  "master_bl_type" TEXT,
  "container_number" TEXT,
  "vessel_name_and_voyage" TEXT,
  "sailing_date" TEXT,
  "destination_port" TEXT,
  "estimated_date_arrival_port" TEXT,
  "consignee_name" TEXT,
  "consignee_street_address_1" TEXT,
  "consignee_street_address_2" TEXT,
  "consignee_city" TEXT,
  "consignee_state" TEXT,
  "consignee_postal_code" TEXT,
  "consignee_country" TEXT,
  "consignee_contact" TEXT,
  "consignee_telephone" TEXT,
  "consignee_irs_tax_id" TEXT,
  "buyer_name" TEXT,
  "buyer_street_address_1" TEXT,
  "buyer_street_address_2" TEXT,
  "buyer_city" TEXT,
  "buyer_state" TEXT,
  "buyer_postal_code" TEXT,
  "buyer_country" TEXT,
  "buyer_contact" TEXT,
  "buyer_telephone" TEXT,
  "ship_to_name" TEXT,
  "ship_to_street_address_1" TEXT,
  "ship_to_street_address_2" TEXT,
  "ship_to_city" TEXT,
  "ship_to_state" TEXT,
  "ship_to_postal_code" TEXT,
  "ship_to_country" TEXT,
  "ship_to_contact" TEXT,
  "ship_to_telephone" TEXT,
  "seller_name" TEXT,
  "seller_street_address_1" TEXT,
  "seller_street_address_2" TEXT,
  "seller_city" TEXT,
  "seller_province" TEXT,
  "seller_postal_code" TEXT,
  "seller_country" TEXT,
  "seller_contact" TEXT,
  "seller_telephone" TEXT,
  "consolidator_name" TEXT,
  "consolidator_street_address_1" TEXT,
  "consolidator_street_address_2" TEXT,
  "consolidator_city" TEXT,
  "consolidator_province" TEXT,
  "consolidator_postal_code" TEXT,
  "consolidator_country" TEXT,
  "consolidator_contact" TEXT,
  "consolidator_telephone" TEXT,
  "stuffing_location_name" TEXT,
  "stuffing_location_street_address_1" TEXT,
  "stuffing_location_street_address_2" TEXT,
  "stuffing_location_city" TEXT,
  "stuffing_location_province" TEXT,
  "stuffing_location_postal_code" TEXT,
  "stuffing_location_country" TEXT,
  "stuffing_location_contact" TEXT,
  "stuffing_location_telephone" TEXT,
  "raw_data" JSONB,
  "extracted_at" TIMESTAMPTZ,
  "reviewed_by" TEXT,
  "reviewed_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "isf_extractions_document_id_key" UNIQUE ("document_id"),
  CONSTRAINT "isf_extractions_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "isf_extractions_transaction_id_idx" ON "aiextraction"."isf_extractions"("transaction_id");
CREATE INDEX IF NOT EXISTS "isf_extractions_house_bl_number_idx" ON "aiextraction"."isf_extractions"("house_bl_number");

CREATE TABLE IF NOT EXISTS "aiextraction"."isf_manufacturers" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "isf_extraction_id" TEXT NOT NULL,
  "manufacturer_name" TEXT,
  "street_address_1" TEXT,
  "street_address_2" TEXT,
  "city" TEXT,
  "province" TEXT,
  "postal_code" TEXT,
  "country" TEXT,
  "po_number" TEXT,
  "hts_code" TEXT,
  "product_code" TEXT,
  "country_of_origin" TEXT,
  CONSTRAINT "isf_manufacturers_isf_extraction_id_fkey" FOREIGN KEY ("isf_extraction_id") REFERENCES "aiextraction"."isf_extractions"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "isf_manufacturers_isf_extraction_id_idx" ON "aiextraction"."isf_manufacturers"("isf_extraction_id");
